name: Feature issue
description: Track a new roadmap item from idea → Definition of Done
title: "feat: <short description>"
labels: [feat]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### 🎯  Goal
        _Short sentence describing the objective._

  - type: textarea
    id: tasks
    attributes:
      label: 🔧  Tasks
      description: |
        Break the feature into atomic check-boxes.  
        Example:
        - [ ] parser accepts Lidl PDF
        - [ ] integration test with sample receipt
      placeholder: |
        - [ ] Task 1
        - [ ] Task 2

  - type: textarea
    id: definition_of_done
    attributes:
      label: ✅  Definition of Done  
      description: |
        Define the criteria for completing this feature.  
        Example:
        - [ ] Unit tests cover happy + edge cases (≥ 90 % branch coverage)
        - [ ] `pre-commit run --all-files` passes
        - [ ] CI pipeline green
        - [ ] Docs section updated (`docs/feature_x.md`)
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2