name: CI (uv + ruff + mypy + pytest)

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

# Cancel stale runs when you push new commits to the same PR
concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v1

      - run: uv sync --group dev --group lint

      - name: Ruff (lint)
        run: uv run ruff check .

      - name: Ruff (format check)
        run: uv run ruff format --check .

      - name: Mypy (types)
        run: uv run mypy .

      - name: Pytest
        run: uv run pytest -q
